# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# Full reference for Standard Spring Boot properties is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# set -Dspring.profiles.active=<dev|sit|int> as JVM argument to run in desired profile
# If no profile is specified explicitly, application will fall back to default profile, which is "local"

spring:
  application:
    name: spring-boot-observability-demo
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  devtools:
    add-properties: false
    restart:
      enabled: false
      exclude: logs/*,application.log,*.log,*.log.*
  main:
    log-startup-info: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    problemdetails:
      enabled: true
  task:
    execution:
      pool:
        queue-capacity: 10000
        core-size: 8
        keep-alive: 60s
        max-size: 64

springdoc:
  show-actuator: true
  group-configs:
    - group: actuator
      display-name: Actuator
      paths-to-match: /actuator/**
    - group: application
      display-name: Application
      paths-to-match: /**
      paths-to-exclude: /actuator/**
  swagger-ui:
    syntaxHighlight:
      activated: true

#------------------------- Actuators configuration -------------------------
# If not specified '/actuator' is taken as default. If specified must start with '/'
#management.endpoints.web.base-path=/
# Set it as "*", if you want to expose all actuator endpoints
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    env:
      show-values: "always"
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  observations:
    key-values:
      #      application: ${spring.application.name}
      org: "${spring.application.org}"
  metrics:
    tags:
      application: "${spring.application.name}"
      org: "${spring.application.org}"
      profiles: "${spring.profiles.active}"
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
          client:
            requests: true
  prometheus:
    metrics:
      export:
        step: 3s
  tracing:
    sampling:
      probability: 1.0
otel:
  exporter:
    otlp:
      endpoint: http://alloy:4318
      #      endpoint: http://localhost:4317
#      endpoint: http://localhost:4318
#      traces:
#        endpoint: "http://alloy:4318/v1/traces"
#      logs:
#        endpoint: "http://alloy:4318/v1/logs"
#      metrics:
#        endpoint: "http://alloy:4318/v1/metrics"
  logs.exporter: otlp
  metrics.exporter: otlp
  traces.exporter: otlp
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: "${spring.application.name}"
        namespace: mlhub

  #Configure metrics generation
  metric.export.interval: 5000 #Export metrics each five seconds
  instrumentation.micrometer.enabled: true #Enabe Micrometer metrics bridge

server:
  port: 8090
  forward-headers-strategy: framework
#  servlet:
#      context-path:
logging:
  level:
    ROOT: info
    '[org.apache.kafka.clients.admin.KafkaAdminClient]': error
    '[org.apache.kafka.clients]': error
debug: false
